name: "Hello Actions"
description: "Greet someone"
author: "paco.luo@gmail.com"

inputs:
  MY_NAME:
    description: "who to greet"
    required: true
    default: "World"
    
runs:
  using: "docker"
  image: "Dockerfile"
  
branding:
  icon: "mic"
  color: "yellow"
